# Generated by Django 4.0.3 on 2022-03-11 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_remove_book_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed_date', models.DateField(auto_now_add=True)),
                ('amount_paid', models.PositiveIntegerField()),
                ('days', models.PositiveIntegerField()),
                ('returned', models.BooleanField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.book')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.subscriber')),
            ],
        ),
    ]
